### ISSUE TITLE
Follow up on offset fix

### ISSUE THREAD

**Issue by danielballan** [NSLS-II-FXI/profile_collection#8]
This seems like a very important commit that should be cherry-picked. Can @mrakitin or @tacaswell explain consequences just to be sure we understand? https://github.com/NSLS-II-FXI/profile_collection/pull/3/commits/31395aa6ccf33a6866ea8e26ee09906609334de2

**Comment by tacaswell** [comment]
It looks like that is fixing a bug that was introduced in that PR not a bug that existed in the current profile.
